import Groq from 'groq-sdk'
import fs from 'fs'

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY })

 const TARGET_FILES = [
  'src/app/layout.tsx',
  'src/app/page.tsx',
  'src/app/(auth)/login/page.tsx',
  'src/app/(auth)/register/page.tsx',
  'src/app/browse/page.tsx',
  'src/app/dashboard/page.tsx',
  'src/app/bookings/page.tsx',
  'src/app/workers/page.tsx',
  'src/app/workers/login/page.tsx',
  'src/app/workers/register/page.tsx',
  'src/app/workers/dashboard/page.tsx',
  'src/app/workers/[id]/page.tsx',
  'src/app/workers/[id]/BookingForm.tsx',
  'src/app/workers/[id]/ReviewForm.tsx',
  'src/app/admin/dashboard/page.tsx',
  'src/components/WorkersAIMatchForm.tsx',
  'src/components/WorkerAvatar.tsx',
  'src/components/worker/WorkerBookingActions.tsx',
  'src/components/admin/AdminWorkerActions.tsx',
  'src/components/ChatWidget.tsx',
  'src/components/signOutButton.tsx',
  'src/components/LanguageToggle.tsx',
]
 

// Wait helper
const wait = (ms) => new Promise((r) => setTimeout(r, ms))

// Groq call with auto retry
async function callGroq(messages, maxTokens = 2000) {
  for (let attempt = 1; attempt <= 5; attempt++) {
    try {
      const response = await groq.chat.completions.create({
        model: 'llama-3.3-70b-versatile',
        max_tokens: maxTokens,
        temperature: 0.1,
        messages,
      })
      return response.choices[0]?.message?.content || ''
    } catch (error) {
      if (error.status === 429) {
        const waitTime = attempt * 20000
        console.log(`   ⏳ Rate limited. Waiting ${waitTime / 1000}s... (attempt ${attempt}/5)`)
        await wait(waitTime)
      } else {
        throw error
      }
    }
  }
  return ''
}

// Extract strings from file — process in small chunks
async function extractStrings(fileContent) {
  // Only send first 4000 chars to stay within token limits
  const chunk = fileContent.slice(0, 4000)

  const text = await callGroq([
    {
      role: 'system',
      content: 'You are a code analyzer. Extract visible UI text from React code. Return ONLY a JSON array of strings. No markdown. No explanation.',
    },
    {
      role: 'user',
      content: `Extract all UI text strings users see on screen. Skip: class names, imports, variable names, routes.

Return format: ["text1", "text2"]

Code:
${chunk}`,
    },
  ], 1000)

  try {
    const start = text.indexOf('[')
    const end = text.lastIndexOf(']')
    if (start === -1 || end === -1) return []
    const parsed = JSON.parse(text.slice(start, end + 1))
    return parsed.filter(
      (s) =>
        typeof s === 'string' &&
        s.trim().length > 1 &&
        s.trim().length < 200 &&
        !s.startsWith('/') &&
        !s.startsWith('http') &&
        !s.includes('className') &&
        !s.includes('=>')
    )
  } catch {
    return []
  }
}

// Translate in small batches of 10
async function translateToUrdu(strings) {
  if (strings.length === 0) return {}

  const result = {}
  const batchSize = 10

  for (let i = 0; i < strings.length; i += batchSize) {
    const batch = strings.slice(i, i + batchSize)

    const text = await callGroq([
      {
        role: 'system',
        content: 'You are an Urdu translator for Pakistani apps. Return ONLY a JSON object. No markdown. No explanation.',
      },
      {
        role: 'user',
        content: `Translate to Pakistani Urdu. Keep unchanged: TrustHire, CNIC, Rs., AI, URLs.

Return format: {"English": "اردو"}

Strings:
${JSON.stringify(batch)}`,
      },
    ], 800)

    try {
      const start = text.indexOf('{')
      const end = text.lastIndexOf('}')
      if (start !== -1 && end !== -1) {
        const parsed = JSON.parse(text.slice(start, end + 1))
        Object.assign(result, parsed)
      }
    } catch {
      // skip failed batch
    }

    // Wait 8 seconds between batches
    if (i + batchSize < strings.length) {
      await wait(8000)
    }
  }

  return result
}

async function buildTranslationsFile(allTranslations) {
  const enObj = {}
  const urObj = {}

  Object.entries(allTranslations).forEach(([en, ur]) => {
    const key = en
      .toLowerCase()
      .replace(/[^a-z0-9\s]/g, '')
      .trim()
      .split(' ')
      .filter(Boolean)
      .map((word, i) => i === 0 ? word : word.charAt(0).toUpperCase() + word.slice(1))
      .join('')
      .slice(0, 50)

    if (key && key.length > 1) {
      enObj[key] = en
      urObj[key] = ur
    }
  })

  const content = `// Auto-generated by TrustHire Translation Agent
// Generated: ${new Date().toISOString()}
// Run "npm run translate" to regenerate

export type Language = 'en' | 'ur'

export const translations = {
  en: ${JSON.stringify(enObj, null, 2)},
  ur: ${JSON.stringify(urObj, null, 2)},
} as const

export type TranslationKey = keyof typeof translations.en
`

  fs.writeFileSync('src/lib/translations.ts', content, 'utf-8')
  console.log('✅ src/lib/translations.ts generated')
}

function buildLanguageContext() {
  const content = `'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'
import { translations, Language, TranslationKey } from '@/lib/translations'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: TranslationKey) => string
  isRTL: boolean
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
  isRTL: false,
})

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')

  useEffect(() => {
    const saved = localStorage.getItem('trusthire-language') as Language
    if (saved === 'en' || saved === 'ur') setLanguageState(saved)
  }, [])

  useEffect(() => {
    document.documentElement.dir = language === 'ur' ? 'rtl' : 'ltr'
    document.documentElement.lang = language
    if (language === 'ur') {
      document.documentElement.style.fontFamily = "'Noto Nastaliq Urdu', serif"
    } else {
      document.documentElement.style.fontFamily = ''
    }
  }, [language])

  function setLanguage(lang: Language) {
    setLanguageState(lang)
    localStorage.setItem('trusthire-language', lang)
  }

  function t(key: TranslationKey): string {
    return translations[language][key] || translations['en'][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL: language === 'ur' }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
`

  fs.mkdirSync('src/context', { recursive: true })
  fs.writeFileSync('src/context/LanguageContext.tsx', content, 'utf-8')
  console.log('✅ src/context/LanguageContext.tsx generated')
}

function buildLanguageToggle() {
  const content = `'use client'

import { useLanguage } from '@/context/LanguageContext'

export default function LanguageToggle({ dark = false }: { dark?: boolean }) {
  const { language, setLanguage } = useLanguage()

  return (
    <div className={\`flex items-center gap-1 rounded-xl p-1 \${dark ? 'bg-white/10' : 'bg-gray-100'}\`}>
      <button
        onClick={() => setLanguage('en')}
        className={\`px-3 py-1.5 rounded-lg text-xs font-bold transition-all \${
          language === 'en'
            ? 'bg-green-600 text-white shadow-sm'
            : dark ? 'text-gray-400 hover:text-white' : 'text-gray-500 hover:text-gray-900'
        }\`}
      >
        EN
      </button>
      <button
        onClick={() => setLanguage('ur')}
        className={\`px-3 py-1.5 rounded-lg text-xs font-bold transition-all \${
          language === 'ur'
            ? 'bg-green-600 text-white shadow-sm'
            : dark ? 'text-gray-400 hover:text-white' : 'text-gray-500 hover:text-gray-900'
        }\`}
        style={{ fontFamily: "'Noto Nastaliq Urdu', serif" }}
      >
        اردو
      </button>
    </div>
  )
}
`

  fs.writeFileSync('src/components/LanguageToggle.tsx', content, 'utf-8')
  console.log('✅ src/components/LanguageToggle.tsx generated')
}

async function runAgent() {
  console.log('🤖 TrustHire Translation Agent')
  console.log('📡 Using Groq — llama-3.3-70b-versatile\n')

  const allTranslations = {}
  let totalStrings = 0

  for (let i = 0; i < TARGET_FILES.length; i++) {
    const filePath = TARGET_FILES[i]

    if (!fs.existsSync(filePath)) {
      console.log(`⚠️  Skipping ${filePath} — not found`)
      continue
    }

    console.log(`📄 [${i + 1}/${TARGET_FILES.length}] ${filePath}`)
    const content = fs.readFileSync(filePath, 'utf-8')

    const strings = await extractStrings(content)
    console.log(`   Found ${strings.length} strings`)

    if (strings.length > 0) {
      const translated = await translateToUrdu(strings)
      const count = Object.keys(translated).length
      console.log(`   Translated ${count} strings ✓`)
      Object.assign(allTranslations, translated)
      totalStrings += strings.length
    }

    // Wait 15 seconds between files
    if (i < TARGET_FILES.length - 1) {
      console.log(`   ⏳ Waiting 15s before next file...`)
      await wait(15000)
    }
  }

  console.log(`\n📊 Total strings: ${totalStrings}`)
  console.log(`📊 Total translations: ${Object.keys(allTranslations).length}`)
  console.log('\n🔨 Generating files...\n')

  await buildTranslationsFile(allTranslations)
  buildLanguageContext()
  buildLanguageToggle()

  console.log('\n🎉 Done! Your app is ready for Urdu.')
  console.log('\n📋 Next steps:')
  console.log('1. Add LanguageProvider to src/app/layout.tsx')
  console.log('2. Add LanguageToggle to your navbars')
  console.log('3. Replace hardcoded text with t("key") in components')
}

runAgent().catch(console.error)